### ISSUE TITLE
Redrawing spectrogram may fail

### ISSUE THREAD

**Issue by MJochim** [IPS-LMU/EMU-webApp#226] opened 2017-07-09 05:58 UTC
(Using Chromium 59)

I tried loading a large file (a 56 minute one of those FrauBovary thingies) and zooming in and out of it. I discovered that the spectrogram sometimes fails to render, leaving the respective signal canvas empty except for the text "rendering ...". In these cases, the following error appears on the console:

```Uncaught TypeError: Cannot read property 'windowSizeInSecs' of null```

I can recover from this error by simply zooming in or out - the spectrogram is then redrawn without a problem. I have not been able to find further hints about when this does or does not happen.

**Comment by raphywink** [comment] 2021-06-02 16:02
just tried this for about 10 mins and couldn't reproduce it. Might have been fixed by accident...

**Closed by raphywink** 2021-06-02 16:02 UTC
