### ISSUE TITLE
Identical bundle names in different sessions highighted as if they were loaded

### ISSUE THREAD

**Issue by MJochim** [IPS-LMU/EMU-webApp#194] opened 2016-05-28 08:57 UTC
# Preparation

You need a database with two bundles that have the same name but belong to different sessions (in the same session they cannot have the same name). You can use ae_emuDB from the emuRdemodata and do this:

``` sh
mkdir 0001_ses
mv 0000_ses/msajc010_bndl 0001_ses/msajc003_bndl
cd 0001_ses/msajc003_bndl
rename 010 003 *
```
# Steps to reproduce
1. Open that database in the emu webapp.
2. Select one of those bundles.
3. Unfold the other session.
# Consequence

The second bundle is highlighted as if it were loaded. No new bundle is loaded, though, before you actually click it.
# Remedy

Only highlight bundles whose bunde _and session_ name match the one currently loaded.

**Comment by raphywink** [comment] 2017-06-16 14:10
This seems to have been fixed a while ago. Could not reproduce the problem any more so closing issue.

**Closed by raphywink** 2017-06-16 14:10 UTC
Labels: bug
