### ISSUE TITLE
hierarchy: click on top element of attribute pulldown causes pull down to collapse 

### ISSUE THREAD

**Issue by florianschiel** [IPS-LMU/EMU-webApp#244] opened 2017-11-07 09:49 UTC
GIT SHA-1: 8596f1786c88c1329fb12206a3fa5cb1fdf85bd6 - master
tested on Chrome and Firefox:
- open hierarchy
- click on the default attribute name in pull down menu of a level
- menu arrow changes from '<' to 'v'
- after that the pull down cannot be used any longer
I have to close the hierchy and start again.

**Comment by MJochim** [comment] 2017-11-07 09:56
I can reproduce this with the ae database integrated into the web app. Clarifictation: You have to click the button label, not the first entry in the pull-down menu.

**Comment by samgregory** [comment] 2022-03-11 03:36
I can't reproduce this bug any more - something has changed in the last 5 years. Time to close?

**Comment by MJochim** [comment] 2022-03-22 18:00
I can't reproduce it either. If only all bugs were magically fixed by waiting five years.

**Closed by MJochim** 2022-03-22 18:00 UTC
Labels: bug
