### ISSUE TITLE
Validation error for .annotJSON pair

### ISSUE THREAD

**Issue by mnrao2001** [IPS-LMU/EMU-webApp#173] opened 2016-01-15 07:06 UTC
For checking the import/pair feature, i uploaded the .wav & .TextGrid file pair it worked with out any issues, but when i generated the .annotJSON from the site and then try to import/pair it back i get error pop-up window saying; 

Error validating annotation file: { "message": "Missing required property: name", "code": 302, "dataPath": "", "schemaPath": "/required/0", "subErrors": null, "stack": "Error: Missing required property: name\n at new f (http://localhost:9000/scripts/4ca856c7.emuwebAppExternal.min.js:9:10114)\n at i.createError (http://localhost:9000/scripts/4ca856c7.emuwebAppExternal.min.js:9:15063)\n at i.validateObjectRequiredProperties (http://localhost:9000/scripts/4ca856c7.emuwebAppExternal.min.js:9:25582)\n at i.validateObject (http://localhost:9000/scripts/4ca856c7.emuwebAppExternal.min.js:9:24784)\n at i.validateAll (http://localhost:9000/scripts/4ca856c7.emuwebAppExternal.min.js:9:18980)\n at Object.g.validate (http://localhost:9000/scripts/4ca856c7.emuwebAppExternal.min.js:9:10985)\n at Object.f.validateJSO (http://localhost:9000/scripts/a7995af7.emuwebApp.min.js:7:6403)\n at http://localhost:9000/scripts/a7995af7.emuwebApp.min.js:7:23506\n at i (http://localhost:9000/scripts/4ca856c7.emuwebAppExternal.min.js:5:13740)\n at http://localhost:9000/scripts/4ca856c7.emuwebAppExternal.min.js:5:13912" }

[M&IExample.zip](https://github.com/IPS-LMU/EMU-webApp/files/91442/M.IExample.zip)

**Comment by raphywink** [comment] 2016-01-15 12:12
Thanks for pointing this out. I was able to reproduce the problem. @georgraess could you have a look at this? Probably a bug in the `toJSO` function of the `textGridParserWorkerClass` Tip: You'll have to remove the `_text` from the TextGrid name to make the drag & drop work.

**Comment by mnrao2001** [comment] 2016-01-16 07:26
We have no issues with .TextGrid file, I had added the suffix "_text.TextGrid" to filename for verbosity so that the sample files are identified easily by you folks for checking. 
But the actual issue is getting the "_annot.json" file to upload/import without any error pop-up as some of the headers like "name", "annotates" &  "sampleRate" seems missing.  

So, in future what will we the "naming convention" adopted for uploading/importing the TextGrid & JSON annotation files?

**Comment by raphywink** [comment] 2016-01-18 09:13
@mnrao2001: For .TextGrid / .wav file pairs the base names of the two file names have to be the same (for example bla.wav & bla.TextGrid). That is why I just gave the hint to my coworker to rename the file so that the drag & drop functionality of the webApp actually works (otherwise there is a base name mismatch). This has nothing to do with the error you reported, which is probably due to a bug in our converter that creates a malformed _annot.json file.

The "naming convention" is and will be that the base names have to match. For files that belong to the  emuDB format (see here https://github.com/IPS-LMU/emuR/blob/master/vignettes/emuDB.Rmd) the base name ends at the underscore (**bla**_annot.json). For other files (SSFF (.fms/.f0/.rms/...)/.wav/.TextGrid/.bpf/...) the base name ends at the dot (**bla**.TextGrid) which is the usual convention.


@georgraess: one thing we should also do is validate the _annot.json file either on creation of the download modal or on click of the download button. This would prevent this sort of thing from happening in the future.

**Comment by georgraess** [comment] 2016-01-18 14:33
Some metadata (name, samplerate, etc) were missing in the data model when dropping textgrids. so when exporting to _annot.json those fields were also missing which led to validation error.
The error was fied in will be included in the next release.... 
...unitl then you can modify "M&IExample_annot.json" like this.


{
  "name": "M&IExample",
  "annotates": "M&IExample.wav",
  "sampleRate": 11025,
  "levels": [
    {
      "name": "levelNr0",
      "type": "SEGMENT",
      "items": [
        {
          "id": 0,
          "sampleStart": 51,
....
....

and it will work (in the meantime)

**Closed** 2016-01-18 15:10 UTC
